""" List with the name of relevant classes for application
"""


# Only the name of the first 400 classes of ImageNet were stored because
# it corresponds to the animal classes in dataset
classes = [
    "tench",
    "goldfish",
    "great white shark",
    "tiger shark",
    "hammerhead",
    "electric ray",
    "stingray",
    "cock",
    "hen",
    "ostrich",
    "brambling",
    "goldfinch",
    "house finch",
    "junco",
    "indigo bunting",
    "robin",
    "bulbul",
    "jay",
    "magpie",
    "chickadee",
    "water ouzel",
    "kite",
    "bald eagle",
    "vulture",
    "great grey owl",
    "European fire salamander",
    "common newt",
    "eft",
    "spotted salamander",
    "axolotl",
    "bullfrog",
    "tree frog",
    "tailed frog",
    "loggerhead",
    "leatherback turtle",
    "mud turtle",
    "terrapin",
    "box turtle",
    "banded gecko",
    "common iguana",
    "American chameleon",
    "whiptail",
    "agama",
    "frilled lizard",
    "alligator lizard",
    "Gila monster",
    "green lizard",
    "African chameleon",
    "Komodo dragon",
    "African crocodile",
    "American alligator",
    "triceratops",
    "thunder snake",
    "ringneck snake",
    "hognose snake",
    "green snake",
    "king snake",
    "garter snake",
    "water snake",
    "vine snake",
    "night snake",
    "boa constrictor",
    "rock python",
    "Indian cobra",
    "green mamba",
    "sea snake",
    "horned viper",
    "diamondback",
    "sidewinder",
    "trilobite",
    "harvestman",
    "scorpion",
    "black and gold garden spider",
    "barn spider",
    "garden spider",
    "black widow",
    "tarantula",
    "wolf spider",
    "tick",
    "centipede",
    "black grouse",
    "ptarmigan",
    "ruffed grouse",
    "prairie chicken",
    "peacock",
    "quail",
    "partridge",
    "African grey",
    "macaw",
    "sulphur-crested cockatoo",
    "lorikeet",
    "coucal",
    "bee eater",
    "hornbill",
    "hummingbird",
    "jacamar",
    "toucan",
    "drake",
    "red-breasted merganser",
    "goose",
    "black swan",
    "tusker",
    "echidna",
    "platypus",
    "wallaby",
    "koala",
    "wombat",
    "jellyfish",
    "sea anemone",
    "brain coral",
    "flatworm",
    "nematode",
    "conch",
    "snail",
    "slug",
    "sea slug",
    "chiton",
    "chambered nautilus",
    "Dungeness crab",
    "rock crab",
    "fiddler crab",
    "king crab",
    "American lobster",
    "spiny lobster",
    "crayfish",
    "hermit crab",
    "isopod",
    "white stork",
    "black stork",
    "spoonbill",
    "flamingo",
    "little blue heron",
    "American egret",
    "bittern",
    "crane",
    "limpkin",
    "European gallinule",
    "American coot",
    "bustard",
    "ruddy turnstone",
    "red-backed sandpiper",
    "redshank",
    "dowitcher",
    "oystercatcher",
    "pelican",
    "king penguin",
    "albatross",
    "grey whale",
    "killer whale",
    "dugong",
    "sea lion",
    "Chihuahua",
    "Japanese spaniel",
    "Maltese dog",
    "Pekinese",
    "Shih-Tzu",
    "Blenheim spaniel",
    "papillon",
    "toy terrier",
    "Rhodesian ridgeback",
    "Afghan hound",
    "basset",
    "beagle",
    "bloodhound",
    "bluetick",
    "black-and-tan coonhound",
    "Walker hound",
    "English foxhound",
    "redbone",
    "borzoi",
    "Irish wolfhound",
    "Italian greyhound",
    "whippet",
    "Ibizan hound",
    "Norwegian elkhound",
    "otterhound",
    "Saluki",
    "Scottish deerhound",
    "Weimaraner",
    "Staffordshire bullterrier",
    "American Staffordshire terrier",
    "Bedlington terrier",
    "Border terrier",
    "Kerry blue terrier",
    "Irish terrier",
    "Norfolk terrier",
    "Norwich terrier",
    "Yorkshire terrier",
    "wire-haired fox terrier",
    "Lakeland terrier",
    "Sealyham terrier",
    "Airedale",
    "cairn",
    "Australian terrier",
    "Dandie Dinmont",
    "Boston bull",
    "miniature schnauzer",
    "giant schnauzer",
    "standard schnauzer",
    "Scotch terrier",
    "Tibetan terrier",
    "silky terrier",
    "soft-coated wheaten terrier",
    "West Highland white terrier",
    "Lhasa",
    "flat-coated retriever",
    "curly-coated retriever",
    "golden retriever",
    "Labrador retriever",
    "Chesapeake Bay retriever",
    "German short-haired pointer",
    "vizsla",
    "English setter",
    "Irish setter",
    "Gordon setter",
    "Brittany spaniel",
    "clumber",
    "English springer",
    "Welsh springer spaniel",
    "cocker spaniel",
    "Sussex spaniel",
    "Irish water spaniel",
    "kuvasz",
    "schipperke",
    "groenendael",
    "malinois",
    "briard",
    "kelpie",
    "komondor",
    "Old English sheepdog",
    "Shetland sheepdog",
    "collie",
    "Border collie",
    "Bouvier des Flandres",
    "Rottweiler",
    "German shepherd",
    "Doberman",
    "miniature pinscher",
    "Greater Swiss Mountain dog",
    "Bernese mountain dog",
    "Appenzeller",
    "EntleBucher",
    "boxer",
    "bull mastiff",
    "Tibetan mastiff",
    "French bulldog",
    "Great Dane",
    "Saint Bernard",
    "Eskimo dog",
    "malamute",
    "Siberian husky",
    "dalmatian",
    "affenpinscher",
    "basenji",
    "pug",
    "Leonberg",
    "Newfoundland",
    "Great Pyrenees",
    "Samoyed",
    "Pomeranian",
    "chow",
    "keeshond",
    "Brabancon griffon",
    "Pembroke",
    "Cardigan",
    "toy poodle",
    "miniature poodle",
    "standard poodle",
    "Mexican hairless",
    "timber wolf",
    "white wolf",
    "red wolf",
    "coyote",
    "dingo",
    "dhole",
    "African hunting dog",
    "hyena",
    "red fox",
    "kit fox",
    "Arctic fox",
    "grey fox",
    "tabby",
    "tiger cat",
    "Persian cat",
    "Siamese cat",
    "Egyptian cat",
    "cougar",
    "lynx",
    "leopard",
    "snow leopard",
    "jaguar",
    "lion",
    "tiger",
    "cheetah",
    "brown bear",
    "American black bear",
    "ice bear",
    "sloth bear",
    "mongoose",
    "meerkat",
    "tiger beetle",
    "ladybug",
    "ground beetle",
    "long-horned beetle",
    "leaf beetle",
    "dung beetle",
    "rhinoceros beetle",
    "weevil",
    "fly",
    "bee",
    "ant",
    "grasshopper",
    "cricket",
    "walking stick",
    "cockroach",
    "mantis",
    "cicada",
    "leafhopper",
    "lacewing",
    "dragonfly",
    "damselfly",
    "admiral",
    "ringlet",
    "monarch",
    "cabbage butterfly",
    "sulphur butterfly",
    "lycaenid",
    "starfish",
    "sea urchin",
    "sea cucumber",
    "wood rabbit",
    "hare",
    "Angora",
    "hamster",
    "porcupine",
    "fox squirrel",
    "marmot",
    "beaver",
    "guinea pig",
    "sorrel",
    "zebra",
    "hog",
    "wild boar",
    "warthog",
    "hippopotamus",
    "ox",
    "water buffalo",
    "bison",
    "ram",
    "bighorn",
    "ibex",
    "hartebeest",
    "impala",
    "gazelle",
    "Arabian camel",
    "llama",
    "weasel",
    "mink",
    "polecat",
    "black-footed ferret",
    "otter",
    "skunk",
    "badger",
    "armadillo",
    "three-toed sloth",
    "orangutan",
    "gorilla",
    "chimpanzee",
    "gibbon",
    "siamang",
    "guenon",
    "patas",
    "baboon",
    "macaque",
    "langur",
    "colobus",
    "proboscis monkey",
    "marmoset",
    "capuchin",
    "howler monkey",
    "titi",
    "spider monkey",
    "squirrel monkey",
    "Madagascar cat",
    "indri",
    "Indian elephant",
    "African elephant",
    "lesser panda",
    "giant panda",
    "barracouta",
    "eel",
    "coho",
    "rock beauty",
    "anemone fish",
    "sturgeon",
    "gar",
    "lionfish",
    "puffer"
]

# Superclasses of species ignoring races
superclasses = [
    "fish",
    "fish",
    "shark",
    "shark",
    "shark",
    "ray",
    "ray",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "hawk",
    "eagle",
    "eagle",
    "owl",
    "salamander",
    "salamander",
    "salamander",
    "salamander",
    "salamander",
    "frog",
    "frog",
    "frog",
    "turtle",
    "turtle",
    "turtle",
    "turtle",
    "turtle",
    "lizard",
    "lizard",
    "lizard",
    "lizard",
    "lizard",
    "lizard",
    "lizard",
    "lizard",
    "lizard",
    "chameleon",
    "lizard",
    "crocodile",
    "alligator",
    "ceratopsian",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "snake",
    "insect",
    "arachnid",
    "arachnid",
    "spider",
    "spider",
    "spider",
    "spider",
    "spider",
    "spider",
    "acarine",
    "insect",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "parrot",
    "parrot",
    "cockatoo",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "duck",
    "duck",
    "duck",
    "swan",
    "elephant",
    "hedgehog",
    "platypus",
    "kangaroo",
    "marsupial",
    "marsupial",
    "cnidarian",
    "actinozoan",
    "stony coral",
    "worm",
    "worm",
    "gastropod",
    "gastropod",
    "gastropod",
    "gastropod",
    "mollusk",
    "mollusk",
    "crab",
    "crab",
    "crab",
    "crab",
    "lobster",
    "lobster",
    "crustacean",
    "crustacean",
    "crustacean",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "bird",
    "penguin",
    "bird",
    "whale",
    "dolphin",
    "sea cow",
    "seal",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "dog",
    "wolf",
    "wolf",
    "wolf",
    "wolf",
    "wolf",
    "wolf",
    "wolf",
    "wolf",
    "fox",
    "fox",
    "fox",
    "fox",
    "cat",
    "cat",
    "cat",
    "cat",
    "cat",
    "big cat",
    "big cat",
    "big cat",
    "big cat",
    "big cat",
    "big cat",
    "big cat",
    "big cat",
    "bear",
    "bear",
    "bear",
    "bear",
    "viverrine",
    "viverrine",
    "beetle",
    "beetle",
    "beetle",
    "beetle",
    "beetle",
    "beetle",
    "beetle",
    "beetle",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "insect",
    "butterfly",
    "butterfly",
    "butterfly",
    "butterfly",
    "butterfly",
    "butterfly",
    "echinoderm",
    "echinoderm",
    "echinoderm",
    "rabbit",
    "rabbit",
    "rabbit",
    "rodent",
    "rodent",
    "squirrel",
    "rodent",
    "rodent",
    "rodent",
    "horse",
    "horse",
    "swine",
    "swine",
    "swine",
    "bovid",
    "bovid",
    "bovid",
    "bovid",
    "sheep",
    "sheep",
    "goat",
    "antelope",
    "antelope",
    "antelope",
    "camel",
    "bovid",
    "mustelid",
    "mustelid",
    "mustelid",
    "mustelid",
    "mustelid",
    "mustelid",
    "mustelid",
    "edentate",
    "sloth",
    "ape",
    "ape",
    "ape",
    "ape",
    "ape",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "monkey",
    "lemur",
    "lemur",
    "elephant",
    "elephant",
    "procyonid",
    "procyonid",
    "fish",
    "fish",
    "fish",
    "fish",
    "fish",
    "fish",
    "fish",
    "fish",
    "fish"
]
